const driverDirectory = [
  ["ALB", "Alexander Albon"],
  ["ALO", "Fernando Alonso"],
  ["ANT", "Andrea Kimi Antonelli"],
  ["BEA", "Oliver Bearman"],
  ["BOR", "Gabriel Bortoleto"],
  ["BOT", "Valtteri Bottas"],
  ["COL", "Franco Colapinto"],
  ["DOO", "Jack Doohan"],
  ["GAS", "Pierre Gasly"],
  ["HAD", "Isack Hadjar"],
  ["HAM", "Lewis Hamilton"],
  ["HUL", "Nico Hulkenberg"],
  ["LAW", "Liam Lawson"],
  ["LEC", "Charles Leclerc"],
  ["MAG", "Kevin Magnussen"],
  ["NOR", "Lando Norris"],
  ["OCO", "Esteban Ocon"],
  ["PER", "Sergio Perez"],
  ["PIA", "Oscar Piastri"],
  ["RUS", "George Russell"],
  ["SAI", "Carlos Sainz"],
  ["SAR", "Logan Sargeant"],
  ["STR", "Lance Stroll"],
  ["TSU", "Yuki Tsunoda"],
  ["VER", "Max Verstappen"],
  ["ZHO", "Zhou Guanyu"],
];

export default driverDirectory;
